\documentclass{article}

\begin{document}
\SweaveOpts{concordance=TRUE}

ozmaps + points


https://support.rstudio.com/hc/en-us/articles/200552056-Using-Sweave-and-knitr
how to export R tables into latex documents with R weave package

<<>>=

require(xtable)
load(iris)

print(
    xtable(
        head(iris)
        ),
        tabular.environment='longtable',
        latex.environments=c("center"), 
        floating=FALSE, 
        include.rownames=FALSE
    )
@ 


\end{document}
